### ISSUE TITLE
XFCE: Help file not found on Time and Date Settings

### ISSUE THREAD

**Issue by Peter-Nesbitt** [linuxmint/mint20-beta#122]
I was trying to change the time settings from UTC form to reflect an am/pm format and ended-up jacking my panel and had to start-over with a new panel and a fresh set of icons.

1. Clicked on the "Whisker" icon to open a menu.
2. Searched for "time" and found "Date and Time" and then right-clicked on the icon to "Add to Panel".
3. The date and time then appear on my panel showing UTC time and I right click on the new panel item to access the preferences, but "Preferences" are greyed-out and not available.
4. I went back to the Whisker menu, searched for "time", clicked on "Date and Time" and a "Time and Date Settings" window appears with a "Help" button in the lower left corner.
5. Still searching for a way to get away from UTC time, I click on the "Help" button and another window appears showing "Help(in bold) Document Not Found" in the title bar.
6. Text in this window displayed the following: "Document Not Found. The URI ‘help:///usr/share/gnome/help/time-admin/C/time-admin.xml’ does not point to a valid page."

All of the above took place on an old MacBook Pro. I also have LM20 Xfce loaded on a Dell Inspiron desktop and reproduced the same error message on that piece of equipment.

Thanks,

Peter

**Comment by xenopeek** [comment]
This is an upstream issue: Time and Date comes from the package [gnome-system-tools](https://packages.ubuntu.com/focal/gnome-system-tools) from the focal repository and following, likely, from [this bug](https://bugs.launchpad.net/ubuntu/+source/gnome-system-tools/+bug/1255235) the Time and Date help has been removed because the help text no longer matches with how the program works. See the `70_gst-yelp.patch` in the `gnome-system-tools_VERSION.debian.tar.xz` archive, which modifies the Makefile to not build `time-admin.xml`. Last release of gnome-system-tools is from 2011 so this is unlikely to be fixed at source.

Shorter steps to reproduce:

1. Open Time and Date from menu;
2. Click Help button;
3. Window opens with message: "Document Not Found. The URI ‘help:///usr/share/gnome/help/time-admin/C/time-admin.xml’ does not point to a valid page."
