### ISSUE TITLE
ubiquity: can't set Russian keyboard layout

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint20-beta#149]
When the default Russian keyboard layout is installed, then after rebooting it changes to English and it is not possible to select the default Russian keyboard layout after rebooting everything changes exactly to English

**Comment by clefebvre** [comment]
I can reproduce the issue in ubiquity.

**Comment by clefebvre** [comment]
I can set the layout to russian in Cinnamon:

- Settings -> Keyboard -> Layout
- Add Russian
- Remove English
- Logout

That works well.

**Comment by clefebvre** [comment]
There is no visual interface to set the system keyboard. To do so, you need to edit:

`/etc/default/keyboard`

**Comment by clefebvre** [comment]
OK, confirmed this is upstream, it happens in Ubuntu 20.04 also.

I'm going to move this to ubiquity and we'll get that fixed in Mint 20.1. I want to redesign the keyboard selection in Ubiquity and make it work differently. Right now, it's trying to match what you see on the screen with a list of translated names it gets from console-setups/keyboard-configuration. It's a huge mess.

I'd like it to source proper keyboard layout codes and names directly by itself and reflect the selection no matter what, without relying on console-setup. We'll tackle this in the next dev cycle (it's not a small task).

**Comment by clefebvre** [comment]
Added to trello for 20.1.
