### ISSUE TITLE
Screen flickering

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint20-beta#174]
I have issue with random screen flickering and random change of screen resolution and black screen in Linux Mint 20 cinnamon edition. My graphic card is Radeon HD 4650, i have this issues since Linux Mint version 18.

**Comment by clefebvre** [comment]
Sorry, that's upstream from us, usually kernel related. You can try to change the vsync method in Settings->General to see if it helps with the flickering. The resolution change is more worrying to me, something must be wrong at driver/kernel level here, that probably affects multiple DEs.

I have to close this issue because it's not something we can fix during this BETA rush.

**Comment by kelebek333** [comment]
Glamor acceleration can cause issues with some older cards. You can try to switch glamor acceleration to exa as follows.

Run following commands.

```
sudo mkdir -p /etc/X11/xorg.conf.d/
sudo touch /etc/X11/xorg.conf.d/20-radeon.conf
sudo xed /etc/X11/xorg.conf.d/20-radeon.conf
```

Copy and paste the lines below into the opened file.

```
Section "Device"
    Identifier "Radeon"
    Driver "radeon"
    Option "AccelMethod" "exa"
    Option "EXAVSync" "yes"
    Option "DRI" "2"
EndSection
```

Restart your PC.
