### ISSUE TITLE
[enhancement] Please add an OpenSSL 1.0 i386 package

### ISSUE THREAD

**Issue by frozenMustelid** [linuxmint/mint20-beta#37]
libcrypto.so.1.0.0:i386 and libssl.so.1.0.0:i386 are both oddly common libraries for many single-player Linux games. One of these games is the popular indie title "Hyper Light Drifter."

Building the amd64 version of the outdated SSL library is easy, but it was much more challenging to try to build the 32-bit version and my internet searches yielded no useful results.

I tried symlinking the .so files from the openssl1.1:i386 package, but the game refused to launch.

Downloading a .deb of the package from Ubuntu 18.04 LTS's repository and installing it allowed my test game (VA-11 Hall A - Cyberpunk Bartender Action) to launch and load into the title screen, but I didn't play any of it, so I don't know if it works or not.

**Comment by kelebek333** [comment]
Hi,

This not a bug. May be you can open a topic on the forum.

**Comment by martinseener** [comment]
I think this is not going to happen as with Mint 20 and onwards, only 64bit builds are made, so no i386/32bit Mint anymore. (But i'm not a dev or member of the Mint team)

**Comment by xenopeek** [comment]
Package libssl1.1 (with files libcrypto.so.1.1 and libssl.so.1.1) is in the repositories for both amd64 and i386. Older versions indeed aren't available. As these are closed source games you can't just recompile them yourself for the target platform. The developers of these games will have to do that for compatibility with Ubuntu 20.04 LTS platform. Do you have these games on Steam? They should still work through Steam as that ships its own runtime. Otherwise, as you say, a workaround is to install older libraries from another source. For help manual compilation I suggest the support channels of openssl.

**Comment by frozenMustelid** [comment]
I own both Hyper Light Drifter and VA-11 Hall A through GOG, which expects Linux users to install their own libraries.

Linux Steam is still slightly broken (Mint 18.2, haven't tested in LM 20 yet), so in my experience GOG is usually more pleasant to use by just sidestepping the launcher issue entirely.
