### ISSUE TITLE
mintsources: Dependency problem when installing muon.

### ISSUE THREAD

**Issue by VaGNaroK** [linuxmint/mint20-beta#52]
when installing muon a dependency error occurs and does not install, either through the terminal or the program center. Is it not in the repository or has it been blocked?

https://postimg.cc/QKxHhBYY

https://postimg.cc/bd3ZLTd7

as not being able to install an alternative package manager is a bit frustrating.

**Comment by enigma131** [comment]
Please provide result in english via command:  **LC_ALL=C sudo apt install muon**. seams you have a dependency problem with software-properties-qt.

**Comment by xenopeek** [comment]
This is caused by `muon` depending on `software-properties-qt` which in turn depends on `python3-software-properties` and requiring specifically version 0.98.9 of that package while Linux Mint has a newer 2.0.1 version of it.

I think it's not installed by default on Linux Mint so you may try installing the older version. Use this command:

`apt install --no-install-recommends python3-software-properties/focal`

Afterwards `muon` should be installable.

**Comment by VaGNaroK** [comment]
I will install mint 20 beta in an English language vm and try to install muon again. anything return. since the tests I'm doing on a production machine.

**Comment by xenopeek** [comment]
You won't be able to install muon just yet. It depends on a package version incompatible with what Mint requires and overriding that may cause other things to break.

**Comment by VaGNaroK** [comment]
I just installed the system on a VM and updated the apt cache, if I even search for the package it shows how installable, but ... it doesn't install.

https://postimg.cc/WdCgG8CT

"You won't be able to install muon just yet. It depends on a package version incompatible with what Mint requires and overriding that may cause other things to break.".

Do you intend to correct this before the final version?

**Comment by smurphos** [comment]
Just some investigation into the cause of this.

muon depends on software-properties-qt, which in turn depends on a specific version of python3-software-properties (= 0.98.9). The latter is in the Ubuntu repos, but is also shipped by the Mint repos with a higher priority. 

The version Mint ships is 2.0.1 - this is a dummy package because mintsources does the job that this package does in ubuntu.

**Comment by clefebvre** [comment]
You can you use the following workaround to install muon:

```
apt install python3-software-properties=0.98.9
apt install muon
```
Can you test muon like this and see if everything is OK? I don't mind freeing the python library, I'm just a bit concerned about software-properties-common which contains a DBUS service.

If muon can work with software-properties-common 2.0.1 then we're OK.

**Comment by VaGNaroK** [comment]
>  python3-software-properties=0.98.9

It worked perfect with your tip. Of course, this method is already good, if it reduces the time you will lose to pack and maintain a dependency, this way will solve it. But it would be good to put these steps for installing the muon with python3-software-properties = 0.98.9 on the site somewhere to help anyone who will install the muon (as was my case).

**Comment by clefebvre** [comment]
No, we can do better. We can free these packages, that way it'll just work out of the box. If that works fine we don't need to pin these.
