### ISSUE TITLE
The firewall is off by default

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint20-beta#60]
I seem to remember that some while ago Mint decided - rightly, one might well think - to have the firewall on by default.

I have just installed Mint 20 Cinnamon in VirtualBox and I was prompted by Mint's 'first steps' to launch the firewall application and enable the firewall. That suggests that the firewall was not on; and indeed upon launching gufw I saw that the firewall was off.

**Comment by hammadimir** [comment]
It was also initially turned off in mint 19.x. We had to manually turn on.

**Comment by frozenMustelid** [comment]
I had to reinstall Mint last month (18.2) and was surprised when I discovered a few days later that the firewall was off. I also remembered the decision to enable firewall by default, and was surprised that it wasn't.

**Comment by clefebvre** [comment]
No, this is by design. The firewall has always been disabled by default. What was added were pointers in the welcome screen to suggest activating it during the first-steps, that's all.

Firewalls may or may not be useful, it really depends on the network of the user. They also may or may not block software from working correctly so it's important the user is aware of the fact that the firewall is active, otherwise he/she might have no idea why some software doesn't work the way it's supposed to be.

So this is something that we suggest in the welcome screen, but it's up to the user to decide whether it's needed and activated or not.
