### ISSUE TITLE
Phantom package - GCC 3.3

### ISSUE THREAD

**Issue by frozenMustelid** [linuxmint/mint20-beta#63]
There's a weird package in the repos. gcc-3.3 appears if you query the apt cache (even if you apt-get update), but if you try to install it apt claims that it can't be found.

![phantom gcc-3 3](https://user-images.githubusercontent.com/31948457/84741516-3567f680-af7d-11ea-830f-a9010942c1a5.png)

I later tried `sudo apt-get install gcc-3.3:i386` but that produce the same result as the command in the screencap.

**Comment by xenopeek** [comment]
I agree it's weird but it's not a beta bug. The apt-cache manpage provides this note for the pkgnames command:

> Note that a package which APT knows of is not necessarily available to download, installable or installed, e.g. virtual packages are also listed in the generated list.

And indeed, this [gcc-3.3](https://packages.ubuntu.com/source/focal/gcc-3.3) package is known by APT because it is the source package of the [libstdc++5](https://packages.ubuntu.com/focal/libstdc++5) package in the focal/universe repository. After you enable source code repositories in Software Sources you can run `apt showsrc gcc-3.3` to confirm the same.
