### ISSUE TITLE
l10n: Cinnamon menu applet

### ISSUE THREAD

**Issue by aureoud-fr85** [linuxmint/mint20-beta#76]
In Menu@cinnamong.org, hovering the shutdown button you see this:
![Menu-Shutdown](https://user-images.githubusercontent.com/66995112/84766620-683bda00-afd1-11ea-91e9-9dc2d0b3421b.png)

We should see "Éteindre l'ordinateur" instead of "Shutdown the computer".

**Comment by clefebvre** [comment]
Places have this issue as well.

**Comment by NikoKrause** [comment]
This has been changed here https://github.com/linuxmint/cinnamon/pull/9243

Translation is from May 31: https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon/fr/+translate?batch=10&show=all&search=Shut+down+the

Cinnamon translations haven't been updated since May 12: https://github.com/linuxmint/cinnamon-translations/commits/master

**Comment by clefebvre** [comment]
Thanks @NikoKrause

**Comment by aureoud-fr85** [comment]
Also, in current version on the BETA media, there is other places not translated:
![menu-i10n-missing](https://user-images.githubusercontent.com/66995112/84894480-31cd9000-b0a1-11ea-9f75-b59253df948b.png)
In third line: "Icon size (pixels)" instead of "Taille d'icône"

![menu2-i10n-missing](https://user-images.githubusercontent.com/66995112/84894486-34c88080-b0a1-11ea-8556-8c9cd9af5080.png)
Second, fourth and sixth lines missing translations for Icon size.

**Comment by clefebvre** [comment]
Fixed.
