### ISSUE TITLE
Impossible to take a window screenshot

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint20-beta#8]
When I take a window screenshot, borders are added around the screenshot, screenshots can't be used.
It's an old bug but it's a very annoying one.
https://github.com/mate-desktop/mate-utils/issues/236

**Comment by enigma131** [comment]
Seems to be a Mate specific bug, Cinnamon working well as before

**Comment by InfoLibre** [comment]
It's a bug with Marco. See mate-desktop/mate-utils#236

**Comment by enigma131** [comment]
Yep I see . I don't use use Mate, I have a small screen resolution here on laptop and with Mate I haven't found the trick to make the taskbar auto hiding (intelligent way of course). Cinnamon (my best) and Xfce have that.

**Comment by InfoLibre** [comment]
Right-click on taskbar and this option doesn't work ?
![Capture du 2020-06-14 13-33-06](https://user-images.githubusercontent.com/3955499/84592161-ccc92e80-ae43-11ea-985a-1f08e9a07aae.png)

**Comment by enigma131** [comment]
Haven't try Mate since a long period. Perhaps a fresh feature. Is this setting a intelligent masking : no masking when there is room on desktop, hiding when a window overlaps taskbar and show taskbar again when windows overlaps taskbar and mouse cursor is going to search the taskbar ? The cinnamon setting below :
![Screenshot from 2020-06-14 11-47-40](https://user-images.githubusercontent.com/31815445/84592415-1bbb9780-ae35-11ea-8cb3-26b6c947bc48.png)

**Comment by InfoLibre** [comment]
Yes, it's the same in MATE.

**Comment by enigma131** [comment]
Ok i will try it later, strange no word for intelligent hiding on Mate menu :)

**Comment by enigma131** [comment]
I've just tested the mate edition. Panel auto hide is working this is not new, but intelligent hide ( hide only if window overlap the panel) is not working. So the feature is missing in mate edition. This comment is off topic and I think not planed for Mate.
