### ISSUE TITLE
[slick-greeter-set-keyboard-layout] multiple definition keyboard layouts

### ISSUE THREAD

**Issue by aureoud-fr85** [linuxmint/mint20-beta#98]
In Linux Mint 19,3 and in 20 BETA, in journald you can see these messages:
![slick-greeter-keyboard](https://user-images.githubusercontent.com/66995112/84902665-647d8580-b0ad-11ea-9e91-35e9bf4e2a3d.png)

There is no reason about complaining.
Therefore, French layout is correctly initialized.
Cosmetic.

**Comment by clefebvre** [comment]
Yes this is done by https://github.com/linuxmint/slick-greeter/blob/master/files/usr/bin/slick-greeter-set-keyboard-layout.

Here's the commit for it: https://github.com/linuxmint/slick-greeter/commit/b12098dc07873b965be9497a00cd5d1a6ed05380

It's harmless and it shows the output of setxkbmap for troubleshooting purpose. setxkbmap itself treats it as a warning because we're setting the same keyboard layout that was already set.

We could ignore the output but we'd lose out on troubleshooting power if that makes sense. We could also test the previous layout and compare it, but we'd be more prone to introducing bugs.

I'd leave it the way it is I think.

I'll close this anyway as it's not a BETA stopper.

**Comment by aureoud-fr85** [comment]
I agree absolutely.
